name: audioplayers_android
description: Android implementation of audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 4.0.3
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers_android
publish_to: 'none'
flutter:
  plugin:
    implements: audioplayers
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin

dependencies:
  audioplayers_platform_interface: 
    git:
      url: 'https://github.com/RookiePlayers/audioplayers_platform_interface-5.0.1'
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^6.1.5
  flame_lint: ^1.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

